<?php

namespace AppBundle\Repository;

/**
 * details_commandeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class details_commandeRepository extends \Doctrine\ORM\EntityRepository
{
}
