<?php

namespace AppBundle\Repository;

/**
 * details_panierRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class details_panierRepository extends \Doctrine\ORM\EntityRepository
{
}
