<?php

namespace AppBundle\Repository;

/**
 * editeurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class editeurRepository extends \Doctrine\ORM\EntityRepository
{
}
