<?php

namespace AppBundle\Repository;

/**
 * livreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class livreRepository extends \Doctrine\ORM\EntityRepository
{
}
