app:
    resource: '@AppBundle/Resources/config/routing.yml'
    
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

fos_user_registration_confirmed:
    path: /register/confirmed
    defaults:
        _controller: FrameworkBundle:Redirect:urlRedirect
        path: /login