App:
  path: / 
  defaults: {_controller:AppBundle:Default:index}

Accueil:
  path: /accueil
  defaults: {_controller:AppBundle:Default:accueil}

Connexion:
  path: /connexion
  defaults: {_controller:AppBundle:Default:connexion}

AjoutUtilisateur:
  path: /addUtilisateur
  defaults: {_controller:AppBundle:Default:addUtilisateur}

Utilisateur_show:
  path: /sport/{id}
  defaults: {_controller:AppBundle:Default:showSport}
  requirements:
    id: '\d+'