App:
  path: /
  defaults: {_controller:AppBundle:Default:index}

accueil:
  path: /accueil
  defaults: {_controller:AppBundle:Default:accueil}

accueil_details:
  path: /accueil_details
  defaults: {_controller:AppBundle:Default:accueil_details}

details:
  path: /details/{id}
  defaults: {_controller:AppBundle:Default:details}

commande:
  path: /commande/{id}
  defaults: {_controller:AppBundle:Default:commande}

